apiVersion: mizar.com/v1
kind: Subnet
metadata:
  name: net21
spec:
  bouncers: 1
  ip: "30.1.0.0"
  prefix: "16"
  bouncers: 2
  vpc: "vpc2"
  status: "Init"
---
apiVersion: mizar.com/v1
kind: Subnet
metadata:
  name: net22
spec:
  bouncers: 1
  ip: "30.2.0.0"
  prefix: "16"
  bouncers: 2
  vpc: "vpc2"
  status: "Init"
